apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize
configMapGenerator:
  - name: app1-cluster-config-values
    files:
      - values.yaml=app1-cluster-config-values.yaml

# configurations:
#   - kustomizeconfig.yaml
