apiVersion: v1
kind: ConfigMap
metadata:
  name: input-config-configmap
data:
  config: |
    {
      "host": "{{ .Values.config.host }}", 
      "environment": "{{ .Values.config.environment }}",
      "application": "{{ .Values.config.application }}",
      "version": "{{ .Values.config.version }}",
      "module": "{{ .Values.config.input }}"
    }