apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1-container
        image: busybox:latest
        env:
        - name: MQTT_SERVER
          value: "mosquitto.mosquitto.svc.cluster.local"
        - name: MQTT_PORT
          value: "1883"
        volumeMounts:
        - mountPath: /etc/daytona
          name: app1-config
      volumes:
      - name: app1-config
        configMap:
          name: config-configmap
